name: "Linting"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1
          submodules: "recursive"
          lfs: false
          token: ${{secrets.COMPANYSTYLESHEET_ACCESS_TOKEN}} # expires 2026-02-01
          # https://github.com/Hochfrequenz/fristenkalender-frontend/settings/secrets/actions/COMPANYSTYLESHEET_ACCESS_TOKEN
          # PAT has repo scope
      - uses: actions/setup-node@v4
        with:
          node-version: "20.13"
          cache: "npm"

      - name: Install modules
        run: npm ci

      - name: Linting
        run: npm run lint:check

      - name: Type-Checking
        run: npm run check
