name: "E2E-Testing"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          submodules: "recursive"
          lfs: false
          token: ${{secrets.COMPANYSTYLESHEET_ACCESS_TOKEN}} # expires 2026-02-01
          # https://github.com/Hochfrequenz/fristenkalender-frontend/settings/secrets/actions/COMPANYSTYLESHEET_ACCESS_TOKEN
          # PAT has repo scope
      - uses: actions/setup-node@v4
        with:
          node-version: "20.13"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set up PlayWright browser
        run: npx playwright install --with-deps

      - name: Build frontend
        run: npm run build

      - name: Start dev server
        run: npm run dev &

      - name: Run Playwright tests
        run: npx playwright test
